Zamówienia_publiczne___/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from public_procurement import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name='base.html'), name='index'),
    path('contract/<int:pk>/', views.ContractDetailView.as_view(), name='detail_contract'),
    path('addContract/', views.AddContractView.as_view(), name='create_contract'),
    path('listContract/', views.ListContractView.as_view(), name='list_contract'),
    path('addContractor/', views.AddTheContractorView.as_view(), name='create_contractor'),
    path('listContractor/', views.ListContractorView.as_view(), name='list_contractor'),
    path('contract/<int:pk>/', views.ContractDetailView.as_view(), name='detail_contract'),
    path('add_comment/<int:contract_pk>/', views.AddCommentView.as_view(), name='add_comment'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('addType/', views.AddTypeProView.as_view(), name='add_type'),
    path('listTyp/', views.ListTypView.as_view(), name='list_typ'),
    path('addProcedure/', views.AddProcedureView.as_view(), name='create_procedure'),
    path('listProcedure/', views.ListProcedureView.as_view(), name='list_procedure' )
]

public_procurement/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class TheContractor(models.Model):
    name = models.CharField(max_length=228)
    number_NIP = models.CharField(max_length=10, null=True)
    nameStreet = models.CharField(max_length=128)
    city = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.name} -  {self.nameStreet}  - {self.city}  - {self.number_NIP}  - {self.nameStreet} - {self.city}"


class Contract(models.Model):
    title = models.CharField(max_length=458)
    contractor = models.ManyToManyField('TheContractor')
    value_contract = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField()
    def __str__(self):
        text = ""
        for s in {self.contractor.all()}:
            for x in s:
               text += x.name
        return f'{self.title} -- {text} --- {self.value_contract} -- {self.start_date}---{self.end_date}'
    def get_absolute_url(self):
        return reverse('detail_contract', args=(self.id,))
class TypeProcurement(models.Model):
    type_procurement = models.CharField(max_length=258)
    contract = models.ForeignKey('Contract', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.type_procurement} -  {self.contract}"


class Procedure(models.Model):
    name_procedure = models.CharField(max_length=558)
    data_initiation = models.DateField()
    value = models.DecimalField(max_digits=15, decimal_places=2)
    end_date_procedure = models.DateField()

    def __str__(self):
        return f"{self.name_procedure}-- {self.data_initiation} ---{self.value}--{self.end_date_procedure} "


class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text} {self.author} {self.contract} {self.date}"

templates/ContractList.html
{% extends 'base.html' %}
{% block content %}
    {% include 'list.html' with objects=contract %}
{% endblock %}

templates/ContractorList.html
{% extends 'base.html' %}
{% block content %}
    {% include 'list.html' with objects=contractor %}
{% endblock %}

templates/ProcedureList.html
{% extends 'base.html' %}
{% block content %}
    {% include 'list.html' with objects=procedure %}
{% endblock %}

templates/TypList.html
{% extends 'base.html' %}
{% block content %}
    {% include 'list.html' with objects=typ_procurement %}
{% endblock %}

templates/addContractor.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p><input type="text" name="name" placeholder="Nazwa Wykonawcy"></p>
        <p><input type="text" name="nip_number" placeholder="Numer NIP"></p>
        <p><input type="text" name="nameStreet" placeholder="ulica"</p>
        <p><input type="text" name="zip_code" placeholder="Kod pocztowy"</p>
        <p><input type="text" name="city" placeholder="Miasto"</p>
        <p><input type="submit"></p>
    </form>
{% endblock %}

templates/addType.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p><input type="text" name="type_procurement" placeholder="Typ zamówienia"></p>
        <label>
            Contract:
        <select name='contract'>
            {%  for c in cont %}
            <option value="{{ c.pk }}">{{ c.title }}</option>
            {% endfor %}
        </select>
        </label>

        <p><input type="submit"></p>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} | Zamówienia Publiczne</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Charmonman:400,700|Open+Sans:400,600,700&amp;subset=latin-ext"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body bgcolor="#ccffcc">
   <h1><center><b><i><ins>Zestawienie Umów</ins></i></b></center></h1>
<nav class="navbar navbar-expand-sm bg-light navbar-light">
    <div class="container-fluid">
            {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'list_contract' %}">Lista zawartych Umów</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_contract' %}">Dodaj Umowę</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_contractor' %}">Dodaj Wykonawcę</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'list_contractor' %}">Lista Wykonawców</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'add_type' %}">Dodaj typ zamówienia</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'list_typ' %}">Rodzaje zamówienia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_procedure' %}">Dodaj Procedury</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'list_procedure' %}">Lista Procedur</a>
            </li>
                <li class="nav-item">
                <a class="nav-link" href="https://isap.sejm.gov.pl/isap.nsf/download.xsp/WDU20220001710/U/D20221710Lj.pdf">Ustawa Zamówień Publicznych</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Wyloguj się</a>
                </li>
            {% else%}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Zaloguj się</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Zarejestruj się</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="https://isap.sejm.gov.pl/isap.nsf/download.xsp/WDU20220001710/U/D20221710Lj.pdf">Ustawa Zamówień Publicznych</a>
                </li>

            {% endif %}
        </ul>
    </div>
</nav>

<div class="container m-4">
    {% block content %}
    {% endblock %}
</div>
<p>{{ date }}</p>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
   <h1><centre>
 <img src="https://scontent-fra3-1.xx.fbcdn.net/v/t1.15752-9/318240540_633452385133620_7106257444177516258_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=ae9488&_nc_ohc=iOsyuKrGM58AX_r1D26&_nc_oc=AQme8Pvo6yE3_rGb8Uxzb5LZforDxouYdISz1FP33M-82ABEu4qhrLApQ9fzLclWBOg&_nc_ht=scontent-fra3-1.xx&oh=03_AdQVlO9zBd7jTt4zmBdgjJRvV5eC5wXPYm7Plag_rdfgMQ&oe=63C40CA4" width="1900" height="1200" alt="" />
   </centre></h1>
</body>
</html>

templates/contract_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card w-75">
        <div class="card-header">
            <span> {{ contract.title }}</span>
        </div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-item">{{ contract.end_date }}</li>
                <li class="list-group-item">{{ contract.start_date_date }}</li>
                <li class="list-group-item">{{ contract.value_contract }}</li>
            </ul>
        </div>
    </div>
    <p>
    <form method="post" action="{% url 'add_comment' contract.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    </p>
    <ul class="list-group">
        {% for comment in contract.comment_set.all %}
            <li class="list-group-item">{{ comment.text }}</li>
        {% endfor %}
    </ul>

{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block content %}
    <p>{{ message }}</p>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/list.html
<ul class="list-group">
    {% for obj in objects %}
        <li class="list-group-item"><a href="{{ obj.get_absolute_url }}"> {{ obj }}</a></li>
    {% endfor %}
</ul>